### ISSUE TITLE
Maps.me doesn't find shortest routes

### ISSUE THREAD

**Issue by SelfishSeahorse** [mapsme/omim#8120] opened 2018-02-17 20:19 UTC
Instead of the shortest routes, sometimes Maps.me finds very exotic and long ones: For example, from [Bern](https://www.openstreetmap.org/node/18477455) to [Sankt Moritz](https://www.openstreetmap.org/node/203453497), Maps.me leads you over the Klausen Pass, instead of using the motorway via Zurich:

![screenshot_2018-02-17-20-57-02](https://user-images.githubusercontent.com/14875493/36345167-29cce294-1426-11e8-835c-4f328d2f277d.png)

This is by far one of the longest routes for travelling from Bern to Sankt Moritz. (Besides, the Klausen Pass is closed in winter.)

Reasonable routes proposed by Google Maps for the same route: 

https://www.google.ch/maps/dir/Bern/St.+Moritz/

The route Maps.me proposed viewed on Google Maps (note the big time discrepancy: 5 h 33 min vs 3 h 48 min!):

https://www.google.ch/maps/dir/Bern/Klausen+Pass,+8751+Spiringen/Glarus+Süd/St+Moritz/

This issue probably is related to #8118.

**Comment by SelfishSeahorse** [comment] 2018-02-17 20:30
I've just found out that from Bern to [Chur](https://www.openstreetmap.org/node/1577255384), which is on the way to Sankt Moritz (and even on the proposed route via Klausen Pass), Maps.me oddly leads one via Zurich ... 

![screenshot_2018-02-17-21-27-30](https://user-images.githubusercontent.com/14875493/36345388-9849c02c-1429-11e8-8642-27ba5431b774.png)

**Comment by burivuh** [comment] 2018-03-19 10:57
@bykoianko Please look at these

**Comment by highbuilder** [comment] 2018-04-27 20:28
Perhaps it would be great, to give 3 different routing solutions to select one, like it is on other maps-apps. (for example apple maps)
![img_49120297966d-1](https://user-images.githubusercontent.com/35878769/39383632-3eeea5f2-4a6a-11e8-93b3-5aceb8de4f13.jpeg)

**Comment by yanncoupin** [comment] 2019-11-07 16:26
It looks like crossing country borders or maybe download zones can sometimes fail in spectacular ways. In the example below, what should be a short route of a few hundred meters ends up being 17km long! Car, foot or bike fail in the same way. I first noticed that issue at least a year ago and the underlying data has always been ok. I hoped it would fix itself but it's still there.
![IMG_2313](https://user-images.githubusercontent.com/209176/68407352-b0fdfb80-0183-11ea-8631-4d30019fc18f.PNG)
![IMG_2314](https://user-images.githubusercontent.com/209176/68407355-b0fdfb80-0183-11ea-9dbd-757c742fda5c.PNG)

**Comment by utack** [comment] 2019-11-13 22:13
I am pretty sure this happened in other places since at least 2 years ago, possibly three  
Are all your maps on the same version (date)?

**Comment by yanncoupin** [comment] 2019-11-13 23:52
Well, I’m not really sure but they’re all up to date if that’s your question. And that was true for the past two years during which I’ve seen this issue

**Comment by bykoianko** [comment] 2019-11-15 08:11
Dear SelfishSeahorse,

Thank you for your report.

I checked the route from Bern to Sankt Moritz you noticed about. I have a route along the motorway via Zurich with ETA 3 hours 30 minutes.
Maps 2019.09.10:
![image](https://user-images.githubusercontent.com/1768114/68926698-2d519980-0797-11ea-9b82-55356b13c4db.png)

Maps 2019.10.19:
![image](https://user-images.githubusercontent.com/1768114/68926822-6d188100-0797-11ea-91a6-b6fb52f58b49.png)

Is that a correct route?

Which map are you using? (Which date?) Do you have all the necessary maps downloaded? I'd like to pay your attention also that to go through the motorway you should not avoid toll roads. There's a setting in Maps.Me.

Regards, Vladimir.

**Comment by SelfishSeahorse** [comment] 2019-11-19 20:48
Hi Vladimir

Thanks for your reply!

> I checked the route from Bern to Sankt Moritz you noticed about. I have a route along the motorway via Zurich with ETA 3 hours 30 minutes.
>
> [...]
> 
> Is that a correct route?
> 
> Which map are you using? (Which date?) Do you have all the necessary maps downloaded? I'd like to pay your attention also that to go through the motorway you should not avoid toll roads. There's a setting in Maps.Me.

Maps.me now shows me the same route (with the latest app and maps available on Android), which i can confirm is the shortest. The time however seems at least half an hour too short (it's impossible to drive at the maximum allowed speed of 80 km/h in the curves), but there's another issue (#8118) for this.

**Comment by bykoianko** [comment] 2019-11-21 15:14
Dear SelfishSeahorse,

thank you for your reply.

> The time however seems at least half an hour too short ....

We're working now to improve ETA in Maps.Me.

Regards,
Vladimir

**Comment by yanncoupin** [comment] 2019-11-22 11:08
Hey Vladimir,

Did you get a chance to reproduce the second problem I reported? No pressure, I'm just checking you don't need additional infos.

Yann

**Comment by bykoianko** [comment] 2020-01-17 11:03
Dear Yann,

are you talking about this place?
![image](https://user-images.githubusercontent.com/1768114/72607215-43174280-3931-11ea-9a58-c9d2f9431861.png)

As far as I see it works correctly now on maps 191124. Could I ask you please to send me the exact coords of start and finish?

Thank you!

Vladimir

**Comment by yanncoupin** [comment] 2020-01-22 00:29
I don’t know if you did something or not but I can confirm that you found the correct location and the issue is gone. No matter what I try, the routing works. I suppose we can close this issue.

**Comment by bykoianko** [comment] 2020-02-25 12:21
Thanks.

**Closed by bykoianko** 2020-02-25 12:21 UTC
