### ISSUE TITLE
Show contour lines

### ISSUE THREAD

**Issue by paride** [mapsme/omim#4179] opened 2016-08-29 15:42 UTC
Now that Maps.me makes use of the altitude profile, for example when calculating bike routes, it should be possible to have it show contour lines on the map. This is very useful when hiking.

**Comment by berolinux** [comment] 2017-08-29 10:21
Contour line data can be generated from SRTM using e.g. phyghtmap or Srtm2Osm
http://wiki.openstreetmap.org/wiki/SRTM
SRTM data is in the public domain, so there are no licensing issues.

Easiest way to get contour lines in OSM compatible format, e.g. for Switzerland:

wget https://planet.osm.ch/switzerland-padded.poly
phyghtmap --source=view1,view3,srtm1,srtm3 --viewfinder-mask=1 --earthdata-user='***' --earthdata-password='***' --polygon=switzerland-padded.poly -o switzerland -j20

Where *** is credentials created by signing up at https://urs.earthdata.nasa.gov/
(The data is freely redistributable, but access to the master server is restricted to registered users. Registration is free and open to anyone.)

**Comment by chstdu** [comment] 2019-10-16 21:29
This is a duplicate of Issue #5722.

Maps.me even uses elevation information from STRM data for their elevation profiles already: https://support.maps.me/hc/en-us/articles/360013576233-Elevation-profile

Please use the existing data to also display elevation contours! Please! We were almost lost in a mountainous region during our holidays because the region looked "innocent" on maps.me!

**Comment by ForkWithMe** [comment] 2020-03-04 11:37
Good news!

Contour lines available in MAPS.ME started from 9.6 version: update the app, then downloaded maps and enable Terrain layer 🏔 

We started to roll out update so it may take some time before this update will be available for everyone.

**Closed by ForkWithMe** 2020-03-04 11:37 UTC

**Comment by chstdu** [comment] 2020-03-05 18:52
Congratulations for the implementation of Terrain layer! This is a huge step for MAPS.ME.

However, the there are far too few contour lines for using MAPS.ME, e.g., for hiking. See the attached example comparison between MAPS.ME and OpenAndroMaps with an Elevate theme.

![MapsMe](https://user-images.githubusercontent.com/1130593/76014885-a9c0e180-5f1a-11ea-8cad-6d0dc350b4d1.png)
![OpenAndroMaps](https://user-images.githubusercontent.com/1130593/76014893-acbbd200-5f1a-11ea-8278-258653b8eceb.png)

**Comment by FireEmerald** [comment] 2020-03-06 08:13
@chstdu You should open a fresh new issue for this. I couldn't test the feature until now because it's not released - but if the contour lines are really like shown on your screenshot, it's like there are none at all...

**Comment by burivuh** [comment] 2020-03-06 08:45
Hi!

Zoom in. Swabia has lines with a 20m step.

We're still working on more appropriate isolines displaying.

**Comment by FabianInostroza** [comment] 2020-06-08 00:26
> Contour line data can be generated from SRTM using e.g. phyghtmap or Srtm2Osm
> http://wiki.openstreetmap.org/wiki/SRTM
> SRTM data is in the public domain, so there are no licensing issues.
> 
> Easiest way to get contour lines in OSM compatible format, e.g. for Switzerland:
> 
> wget https://planet.osm.ch/switzerland-padded.poly
> phyghtmap --source=view1,view3,srtm1,srtm3 --viewfinder-mask=1 --earthdata-user='_**' --earthdata-password='**_' --polygon=switzerland-padded.poly -o switzerland -j20
> 
> Where *** is credentials created by signing up at https://urs.earthdata.nasa.gov/
> (The data is freely redistributable, but access to the master server is restricted to registered users. Registration is free and open to anyone.)
> 
> Using this mechanism generates OSM ways with tag k="contour" v="elevation" or tag k="contour_ext" v="elevation_major"

Hi, how can I use the output if phyghtmap to add the contour lines in maps.me? I've used phyghtmap to generate contour lines for garmin devices and the method is to generate a second map that overlays the openstreetmap data. 
I guess I could merge the openstreetmap data and the output of phyghtmap but then how do maps.me know what contour lines to draw at a certain zoom level?.
It would be helpful if you tell the procedure to generate the contour lines for maps.me because the map generation takes a lot of time.
I'm stuck on an old version of the app.

**Comment by tatiana-yan** [comment] 2020-06-08 08:31
Hello. We use custom binary maps format. We need custom format because we can optimise it and have rather small offline maps. Contour lines are built in our offline data so it's not so easy to customise it.
We use SRTM and ASTER tiles for contour lines. We process it with tool https://github.com/mapsme/omim/blob/master/topography_generator/ which allows us to set custom parameters for each country (step, smoothing etc.). We try to find balance between data size and accuracy for each country but of course for some users it's not good.

To generate custom contour lines one should:

- download SRTM/ASTER data
- generate contour lines tiles with topography_generator
- generate packed contour lines with topography_generator
- set ISOLINES_PATH to directory with *.isolines files in map generator config file (map_generator.ini)
- generate maps with map generator https://github.com/mapsme/omim/tree/master/tools/python/maps_generator

All our map generation tools are opensource and comes with instruction or built-in docs.
