### ISSUE TITLE
Add support for rendering contour lines

### ISSUE THREAD

**Issue by berolinux** [mapsme/omim#5722] opened 2017-03-29 23:12 UTC
Hi,
I'd like to add rendering contour lines -- I know how to get the contour line data from SRTM and convert them into a OSM-like format, and merge that into an osm file (phyghtmap will do the trick -- afterwards, contour lines are ways with tag k="contour" v="elevation" or tag k="contour_ext" v="elevation_major".

I'm new to the maps.me codebase though (just submitted a few fixes to make it compile for me), could use some pointers to get started (making sure the contours make it into the mwm files and then get rendered [mapcss modification?]).

**Comment by chstdu** [comment] 2018-06-03 23:18
Contour lines would be really great, especially for hiking and cycling. At the moment, I have to use another app with [OpenAndroMaps](https://openandromaps.org), but all these duplicate map files take so much space on my phone! Please support contour lines or - even better - directly support mapsforge maps (with contour lines) [like these other tools](https://github.com/mapsforge/mapsforge/blob/master/docs/Mapsforge-Applications.md), too.

**Comment by unic0der** [comment] 2019-03-06 10:23
Open data for contour lines are now available for most countries in the world and I know A LOT of people using Maps.me for hiking. It's about time to get started with this.

**Comment by chstdu** [comment] 2019-10-16 21:24
Maps.me even uses elevation information from STRM data for their elevation profiles: https://support.maps.me/hc/en-us/articles/360013576233-Elevation-profile

Please use the existing data to also display elevation contours! Please! We were almost lost in a mountainous region during our holidays because the region looked "innocent" on maps.me!

**Comment by chstdu** [comment] 2019-10-16 21:31
This is a duplicate of Issue #4179.

**Comment by robsmith11** [comment] 2019-10-23 15:48
I generally prefer Maps.ME, but I ended up installing OsmAnd again so that I can have contour lines for hiking.

**Comment by ForkWithMe** [comment] 2020-03-04 11:37
Good news!

Contour lines available in MAPS.ME started from 9.6 version: update the app, then downloaded maps and enable Terrain layer 🏔 

We started to roll out update so it may take some time before this update will be available for everyone.

**Closed by ForkWithMe** 2020-03-04 11:37 UTC

**Comment by chstdu** [comment] 2020-03-05 18:57
Congratulations!

However, please see my comment at #4179 why the contour lines are not yet enough for hiking.
