### ISSUE TITLE
Include object information in notes

### ISSUE THREAD

**Issue by SomeoneElseOSM** [mapsme/omim#6136] opened 2017-05-26 13:01 UTC
Quoting from https://lists.openstreetmap.org/pipermail/talk/2017-May/078061.html : 

"Why doesn't damn MAPS.ME produce those bloody notes with the name of
the place instead of "The place" ? That way they could be useful
instead of being a nuisance."

**Comment by Zverik** [comment] 2017-05-27 12:16
Duplicate of #6016. Already fixed, see https://www.openstreetmap.org/note/1009059 for an example.

**Closed by Zverik** 2017-05-27 12:16 UTC
