### ISSUE TITLE
Disappearing toolbar

### ISSUE THREAD

**Issue by legovini** [mapsme/omim#4374] opened 2016-09-23 14:40 UTC
With the upgrade that came out today the bottom toolbar often disappears and there is no way to interact with the app. This happens for example when cancelling a routing operation. This didn't happen with the previous version. (Nexus 6, stock Android N.)

**Comment by Norbert80** [comment] 2016-09-24 23:09
I experience the same problem.

**Comment by burivuh** [comment] 2016-09-26 16:31
Fixed in 6.4.3

**Closed by burivuh** 2016-09-26 16:31 UTC

**Comment by Norbert80** [comment] 2016-10-10 09:14
@legovini I experience this issue again with build "6.4.3-Google". So it seems to be not fully covered by your fix.

**Comment by legovini** [comment] 2016-10-10 12:56
@Norbert80 the fix was not mine, anyway I can't reproduce the problem with 6.4.3-Google.

**Comment by Norbert80** [comment] 2016-10-10 13:33
It still happens sporadically. Before the fix it happend more often and reproducible.

**Comment by Norbert80** [comment] 2016-10-13 22:32
My report of experiencing this bug seems to be a duplicate of #4434.
